server:
 port: 9000

searcherservice:
  ribbon:  
    listOfServers: localhost:8060,localhost:8061,localhost:8062
    ServerListRefreshInterval: 15000 
    
crawlerservice:
  ribbon:  
    listOfServers: localhost:8070,localhost:8071,localhost:8072
    ServerListRefreshInterval: 15000     